### PR TITLE
feat: add static/index.html

### PR DESCRIPTION
**Pull request by iamclaytonray**
I added a static directory (because HTML is static code) for the main/root/index HTML file to live in, as well as any other static files and assets that we may need to add in later. This code was mostly just boilerplate from VS Code's autocomplete amazingness but essentially, it just creates the foundation document to be used in the browser (DOM). I added a level one heading that says "Hello World" and a paragraph that says "Moarrr COBOL" because we need more COBOL in the world 😂 😂

### CODE REVIEW

**Comment by iamclaytonray** [comment]
Sorry dude; I like to live life with a lil' flair sometimes 😂

**Comment by evenstensberg** [comment]
No worries, awesome that you did this! Could you fill out the Pull Request Description so that other people will look at the change and understand what you have done? Thanks, klovu ❤️

**Comment by bhavayAnand9** [comment]
Maybe we should add a pull request template.

**Comment by iamclaytonray** [comment]
@evenstensberg - I'm not sure what to add. Like, instructions on how I got from nothing to PR? Or explaining what each part of the document is and why I added it? (ps: I just wrote html:5 in vscode to boilerplate that stuff, haha. But I can explain it

**Comment by evenstensberg** [comment]
@bhavayAnand9 that would be great. Also, this task is for everyone. Even though @iamclaytonray submitted a PR I would like everyone to do so, so that they know that they can do it! 👍 

A small section of what the change is would be great. In Open Source those are often filled out for people to know what has changed in the code and why. A why here isn't needed but a small section with what you've changed along with how you did it would be great! 💙

**Comment by iamclaytonray** [comment]
@evenstensberg - like that?

**Comment by bhavayAnand9** [comment]
Add a link to the issue which you're fixing. It's a good practice.

**Comment by iamclaytonray** [comment]
Typically, I'd include it in the commit to close the issue but I digress 🤷‍♂️

**Pull request merged**
